version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Choose either one of the orbs below
  # welcome: circleci/welcome-orb@0.4.1
  # aws-cli: circleci/aws-cli@2.0.3
# Define the jobs we want to run for this project
jobs:
#  create_infrastructure: 
#      docker:
#        - image: amazon/aws-cli
#      steps:
#        - checkout 
#        - run:
#            name: Create Cloudformation Stack
#            command: |
#              aws cloudformation deploy \
#                --template-file template.yml \
#                --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
#                --region us-east-1
 configure_infrastructure: 
  docker:
    - image: python:3.7-alpine3.11 
  steps:
    - checkout
    - add_ssh_keys:
            # You can get this ID in the section where you registered the SSH Key
            fingerprints: ["75:11:74:14:43:18:dc:4d:78:35:20:a3:54:bc:2a:ca"] 
    - run:
        name: Install Ansible
        command: |
          apk add --update ansible    
    - run:
        name: Run Playbook and Configure server
        command: |
          ansible-playbook -i inventory main-remote.yml
 smoke_test:
  docker:
    - image: alpine
  steps:
    - run: apk add --update curl
    - run:
        name: perform a smoke test
        command: |
          URL="https://blog.udacity.com"
          if curl -s --head ${URL}
          then
            return 0
          else
            return 1
          fi
  
# Sequential workflow
workflows:
  # Name the workflow
  myWorkflow:
    jobs:
      # - create_infrastructure
      - configure_infrastructure
      - smoke_test:
          requires:
            - configure_infrastructure            
